project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"
    - "!files_for_project_backlog/**"

website:
  title: "Felix Lennert"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Selected Work
      - href: research.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script data-goatcounter="https://fellennert.goatcounter.com/count"
                  async src="https://gc.zgo.at/count.js"></script>



